name: 🚀 deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
      - run: cd infrastructure && terraform init
      - run: cd infrastructure && terraform plan -out tf.plan
      - run: cd infrastructure && terraform apply -auto-approve tf.plan