name: 🚀 on push to master
on:
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: npm install
      - run: npm run test:unit
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: npm install
      - run: npm run test:e2e:serve-files &
      - run: npm run test:e2e:cypress-run

  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs:
      - unit
      - e2e
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
      - run: cd infrastructure && terraform init
      - run: cd infrastructure && terraform plan -out tf.plan
      - run: cd infrastructure && terraform apply -auto-approve tf.plan
