name: 🚀 on pull request to master
on:
  pull_request:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: npm install
      - run: npm run test:unit
 e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: npm install
      - run: npm run test:e2e:serve-files &
      - run: npm run test:e2e:cypress-run
